name: Django Tests

on:
  pull_request:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest

    # Configuration de PostgreSQL
    services:
      postgres:
        image: postgres:18.1-bookworm
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: password
          POSTGRES_DB: checklist
        ports:
          - 5432:5432
        # On attend que postgres soit prÃªt avant de lancer le job
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true # Active le cache automatique pour uv

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: uv sync --all-groups

      - name: Run Tests
        env:
          DATABASE_URL: postgres://admin:password@localhost:5432/checklist
          SECRET_KEY: "ci-secret-key"
          DEBUG: off
          FERNET_KEY: "my_secret_key"
          TIME_ZONE: "Europe/Paris"
        run: |
          cd checklistapp
          uv run pytest

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v6
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: "**/pytest.xml"
